data:
  train_path: data/obs_gen.0.1/train.json
  train_batch_size: 48
  train_num_workers: 4
  val_path: data/obs_gen.0.1/valid.json
  val_batch_size: 128
  val_num_workers: 4
  test_path: data/obs_gen.0.1/test.json
  test_batch_size: 128
  test_num_workers: 4
  word_vocab_file: vocabs/word_vocab.txt

model:
  hidden_dim: 64
  pretrained_word_embedding_path: embedding/crawl-300d-2M.vec
  word_emb_dim: 300
  node_vocab_path: vocabs/node_vocab.txt
  node_emb_dim: 100
  relation_vocab_path: vocabs/relation_vocab.txt
  relation_emb_dim: 32
  text_encoder_num_blocks: 1
  text_encoder_num_conv_layers: 5
  text_encoder_kernel_size: 5
  text_encoder_num_heads: 1
  graph_encoder_num_cov_layers: 6
  graph_encoder_num_bases: 3
  text_decoder_num_blocks: 1
  text_decoder_num_heads: 1

train:
  learning_rate: 5e-4
  sample_k_gen_obs: 5
  steps_before_backprop: 5

pl_trainer:
  max_epochs: 6250  # 300000 / 48

run_test: false

defaults:
  - logger: null
