data:
  train_path: data/obs_gen.0.1/train.json
  train_batch_size: 48
  train_num_workers: 4
  val_path: data/obs_gen.0.1/valid.json
  val_batch_size: 128
  val_num_workers: 4
  test_path: data/obs_gen.0.1/test.json
  test_batch_size: 128
  test_num_workers: 4
  word_vocab_file: vocabs/word_vocab.txt

model:
  pretrained_word_embedding_path: embedding/crawl-300d-2M.vec
  word_vocab_path: vocabs/word_vocab.txt
  node_vocab_path: vocabs/node_vocab.txt
  relation_vocab_path: vocabs/relation_vocab.txt

train:
  learning_rate: 5e-4
  sample_k_gen_obs: 5
  steps_for_lr_warmup: 10000

pl_trainer:
  max_epochs: 6250  # 300000 / 48
  truncated_bptt_steps: 5

eval:
  test_only: false
  checkpoint_path: null
  max_decode_len: 200

defaults:
  - model_size: original
  - logger: null
