data:
  base_data_dir: "data/rl.0.2"
  difficulty_level: 1
  train_data_size: 20
  train_max_episode_steps: 50
  train_game_batch_size: 25
  replay_buffer_capacity: 500000
  replay_buffer_populate_episodes: 100
  train_sample_batch_size: 64
  eval_max_episode_steps: 100
  eval_game_batch_size: 20

model:
  word_vocab_path: vocabs/word_vocab.txt
  node_vocab_path: vocabs/node_vocab.txt
  relation_vocab_path: vocabs/relation_vocab.txt
  pretrained_graph_updater:
    ckpt_path: pretrained/graph-updater-obs-gen.ckpt
    word_vocab_path: vocabs/word_vocab.txt
    node_vocab_path: vocabs/node_vocab.txt
    relation_vocab_path: vocabs/relation_vocab.txt
  hidden_dim: 64
  word_emb_dim: 300
  node_emb_dim: 100
  relation_emb_dim: 32
  text_encoder_num_blocks: 1
  text_encoder_num_conv_layers: 5
  text_encoder_kernel_size: 5
  text_encoder_num_heads: 1
  graph_encoder_num_cov_layers: 6
  graph_encoder_num_bases: 3
  action_scorer_num_heads: 1

train:
  training_step_freq: 50
  replay_buffer_reward_threshold: 0.1
  target_net_update_frequency: 500
  epsilon_anneal_from: 1.0
  epsilon_anneal_to: 0.1
  epsilon_anneal_episodes: 20000
  reward_discount: 0.9
  ckpt_patience: 3

pl_trainer:
  max_epochs: 4000  # max_episodes/train_game_batch_size = 100000/25
  gradient_clip_val: 5

defaults:
  - logger: null
  - data: null
